[phases.setup]
cmds = [
    "apt-get update",
    "apt-get install -y wget gnupg curl unzip fonts-freefont-ttf libglib2.0-0 libnss3 libnspr4 libdbus-1-3 libatk1.0-0 libatk-bridge2.0-0 libatspi2.0-0 libx11-6 libxcomposite1 libxdamage1 libxext6 libxfixes3 libxrandr2 libgbm1 libxcb1 libxkbcommon0 libasound2",
]

[phases.install]
cmds = [
    "pip install -r requirements.txt",
    "playwright install --force chromium",
    "playwright install-deps",
]

[start]
cmd = "python main.py"