[phases.setup]
cmds = [
    "apt-get update",
    "apt-get install -y wget gnupg curl unzip fonts-freefont-ttf",
    # Install exact dependencies from the error message with t64 variants
    "apt-get install -y libglib2.0-0t64 libnss3 libnspr4 libdbus-1-3 libatk1.0-0t64 libatk-bridge2.0-0t64 libatspi2.0-0t64 libx11-6 libxcomposite1 libxdamage1 libxext6 libxfixes3 libxrandr2 libgbm1 libxcb1 libxkbcommon0 libasound2t64",
    # Additional dependencies that might be needed
    "apt-get install -y libcups2 libdrm2 libxshmfence1 libxkbcommon-x11-0",
]

[phases.install]
cmds = [
    "pip install -r requirements.txt",
    "playwright install --force chromium",
    "playwright install-deps",
]

[start]
cmd = "python main.py"